"""initial schema

Revision ID: 310bd16d3308
Revises: 
Create Date: 2026-08-14 14:45:58.641727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '310bd16d3308'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # users.username and users.email use CITEXT, which requires the
    # `citext` extension to exist before that table is created. A
    # manually-installed extension is not guaranteed on fresh databases.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_categories',
    sa.Column('category_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('slot', sa.Enum('HAIR', 'HAT', 'TOP', 'BOTTOM', 'SHOES', 'ACCESSORY', name='avatar_slot'), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('coin_transaction_types',
    sa.Column('type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('direction', sa.Enum('CREDIT', 'DEBIT', name='transaction_direction'), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('competition_status',
    sa.Column('status_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('notification_types',
    sa.Column('type_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('products',
    sa.Column('product_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('biography', sa.String(), nullable=True),
    sa.Column('coin_balance', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('winning_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coin_balance >= 0', name='ck_users_coin_balance_non_negative'),
    sa.CheckConstraint('winning_streak >= 0', name='ck_users_winning_streak_non_negative'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auth_providers',
    sa.Column('auth_provider_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', 'APPLE', name='auth_provider_type'), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('auth_provider_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_auth_providers_provider_identity')
    )
    op.create_table('avatars',
    sa.Column('avatar_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avatar_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('clothing_items',
    sa.Column('item_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'UPCOMING', name='clothing_availability'), server_default='AVAILABLE', nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_clothing_items_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['clothing_categories.category_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('competition_requests',
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('challenger_id', sa.UUID(), nullable=False),
    sa.Column('opponent_id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', name='competition_request_status'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('challenger_id <> opponent_id', name='ck_competition_requests_no_self_challenge'),
    sa.CheckConstraint('duration_minutes IN (30, 60, 360, 1440)', name='ck_competition_requests_duration_allowed_values'),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('device_tokens',
    sa.Column('device_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', name='device_platform'), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('push_token')
    )
    op.create_index('ix_device_tokens_user_id_is_active', 'device_tokens', ['user_id', 'is_active'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('followee_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name='ck_follows_no_self_follow'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_index('ix_follows_followee_id', 'follows', ['followee_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.SmallInteger(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['type_id'], ['notification_types.type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_user_id_is_read_created_at', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('qr_codes',
    sa.Column('qr_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('coin_value', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REDEEMED', 'EXPIRED', name='qr_status'), server_default='ACTIVE', nullable=False),
    sa.Column('redeemed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'REDEEMED') = (redeemed_by_user_id IS NOT NULL AND redeemed_at IS NOT NULL)", name='ck_qr_codes_redemption_fields_consistent'),
    sa.CheckConstraint('coin_value > 0', name='ck_qr_codes_coin_value_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('qr_id')
    )
    op.create_index(op.f('ix_qr_codes_code'), 'qr_codes', ['code'], unique=True)
    op.create_table('avatar_equipment',
    sa.Column('avatar_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Enum('HAIR', 'HAT', 'TOP', 'BOTTOM', 'SHOES', 'ACCESSORY', name='avatar_slot'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('equipped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.avatar_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.item_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('avatar_id', 'slot')
    )
    op.create_table('competitions',
    sa.Column('competition_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('challenger_id', sa.UUID(), nullable=False),
    sa.Column('opponent_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('prize_pool', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_votes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), sa.Computed("start_time + (duration_minutes * interval '1 minute')", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('challenger_id <> opponent_id', name='ck_competitions_no_self_challenge'),
    sa.CheckConstraint('winner_id IS NULL OR winner_id IN (challenger_id, opponent_id)', name='ck_competitions_winner_is_participant'),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['competition_requests.request_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['competition_status.status_id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('competition_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('user_wardrobe',
    sa.Column('wardrobe_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['clothing_items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wardrobe_id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_wardrobe_no_duplicate_purchase')
    )
    op.create_table('votes',
    sa.Column('vote_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competition_id', sa.UUID(), nullable=False),
    sa.Column('voter_id', sa.UUID(), nullable=False),
    sa.Column('voted_for_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('voter_id <> voted_for_user_id', name='ck_votes_no_self_vote'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voted_for_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voter_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('competition_id', 'voter_id', name='uq_votes_one_per_user_per_competition')
    )
    op.create_table('coin_transactions',
    sa.Column('transaction_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.UUID(), nullable=True),
    sa.Column('wardrobe_id', sa.UUID(), nullable=True),
    sa.Column('vote_id', sa.UUID(), nullable=True),
    sa.Column('competition_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount <> 0', name='ck_coin_transactions_amount_nonzero'),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.competition_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qr_id'], ['qr_codes.qr_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['coin_transaction_types.type_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.vote_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wardrobe_id'], ['user_wardrobe.wardrobe_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_coin_transactions_created_at'), 'coin_transactions', ['created_at'], unique=False)
    op.create_index('ix_coin_transactions_user_id_created_at', 'coin_transactions', ['user_id', 'created_at'], unique=False)

    # ### seed lookup tables ###
    op.bulk_insert(
        sa.table(
            "clothing_categories",
            sa.column("category_name", sa.String()),
            sa.column("slot", postgresql.ENUM(name="avatar_slot", create_type=False)),
        ),
        [
            {"category_name": "Hairstyles", "slot": "HAIR"},
            {"category_name": "Hats", "slot": "HAT"},
            {"category_name": "Tops", "slot": "TOP"},
            {"category_name": "Bottoms", "slot": "BOTTOM"},
            {"category_name": "Sneakers", "slot": "SHOES"},
            {"category_name": "Sunglasses", "slot": "ACCESSORY"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "coin_transaction_types",
            sa.column("type_name", sa.String()),
            sa.column("direction", postgresql.ENUM(name="transaction_direction", create_type=False)),
        ),
        [
            {"type_name": "qr_redemption", "direction": "CREDIT"},
            {"type_name": "competition_reward", "direction": "CREDIT"},
            {"type_name": "clothing_purchase", "direction": "DEBIT"},
            {"type_name": "vote_cast", "direction": "DEBIT"},
            {"type_name": "refund", "direction": "CREDIT"},
            {"type_name": "admin_adjustment", "direction": "CREDIT"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "competition_status",
            sa.column("status_name", sa.String()),
        ),
        [
            {"status_name": "active"},
            {"status_name": "completed"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "notification_types",
            sa.column("type_name", sa.String()),
        ),
        [
            {"type_name": "new_follower"},
            {"type_name": "competition_request"},
            {"type_name": "competition_accepted"},
            {"type_name": "competition_won"},
            {"type_name": "competition_lost"},
            {"type_name": "qr_redeemed"},
            {"type_name": "clothing_purchased"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_coin_transactions_user_id_created_at', table_name='coin_transactions')
    op.drop_index(op.f('ix_coin_transactions_created_at'), table_name='coin_transactions')
    op.drop_table('coin_transactions')
    op.drop_table('votes')
    op.drop_table('user_wardrobe')
    op.drop_table('competitions')
    op.drop_table('avatar_equipment')
    op.drop_index(op.f('ix_qr_codes_code'), table_name='qr_codes')
    op.drop_table('qr_codes')
    op.drop_index('ix_notifications_user_id_is_read_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_follows_followee_id', table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_device_tokens_user_id_is_active', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_table('competition_requests')
    op.drop_table('clothing_items')
    op.drop_table('avatars')
    op.drop_table('auth_providers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('notification_types')
    op.drop_table('competition_status')
    op.drop_table('coin_transaction_types')
    op.drop_table('clothing_categories')
    # ### end Alembic commands ###
