"""
Pydantic schemas for the admin clothing-management module.

Input schemas accept only catalog fields an administrator may set —
item_id and created_at are database-owned and deliberately absent, so a
client can never supply or change them. The category is referenced by its
existing clothing_categories.category_id (the admin picks from the real
lookup rows; the slot is inherited from the category record and is never
client-supplied). price mirrors the DB CHECK constraint
(ck_clothing_items_price_non_negative): >= 0. availability_status only
accepts the existing ClothingAvailability enum values.

Output schemas expose exactly the administrative catalog view: flat
category context (id/name/slot), price, availability, collection_id and
created_at — nothing internal beyond that.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models import AvatarSlot, ClothingAvailability


def _require_non_empty(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        raise ValueError("must not be empty")
    return stripped


class ClothingAdminCategory(BaseModel):
    """One clothing_categories lookup row for the admin form dropdown."""

    model_config = ConfigDict(from_attributes=True)

    category_id: int
    category_name: str
    slot: AvatarSlot


class ClothingAdminCreate(BaseModel):
    """Body of POST /admin/clothing.

    item_id/created_at are generated by the database; slot comes from the
    selected category row. availability_status defaults to AVAILABLE,
    mirroring the column's server_default.
    """

    name: str = Field(max_length=255, description="Item display name")
    description: str | None = Field(
        default=None, max_length=1000, description="Optional shop description"
    )
    category_id: int = Field(
        ge=1,
        le=32767,
        description="Existing clothing_categories.category_id (SMALLINT)",
    )
    price: int = Field(ge=0, description="Price in coins (>= 0, per DB CHECK)")
    image_url: str = Field(max_length=2048, description="Catalog image URL")
    availability_status: ClothingAvailability = ClothingAvailability.AVAILABLE
    collection_id: uuid.UUID | None = Field(
        default=None,
        description="Optional future-collections tag (plain column, no FK yet)",
    )

    @field_validator("name", "image_url")
    @classmethod
    def non_empty(cls, value: str) -> str:
        return _require_non_empty(value)

    @field_validator("description")
    @classmethod
    def non_empty_description(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _require_non_empty(value)


class ClothingAdminUpdate(BaseModel):
    """Body of PATCH /admin/clothing/{item_id}.

    Every field optional (single-field PATCH); omitted fields are never
    written. item_id and created_at cannot be referenced at all.
    Sending explicit null clears description/collection_id.
    """

    name: str | None = Field(default=None, max_length=255)
    description: str | None = Field(default=None, max_length=1000)
    category_id: int | None = Field(default=None, ge=1, le=32767)
    price: int | None = Field(default=None, ge=0)
    image_url: str | None = Field(default=None, max_length=2048)
    availability_status: ClothingAvailability | None = None
    collection_id: uuid.UUID | None = None

    @field_validator("name", "image_url")
    @classmethod
    def non_empty(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _require_non_empty(value)

    @field_validator("description")
    @classmethod
    def non_empty_description(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _require_non_empty(value)


class ClothingAdminRead(BaseModel):
    """Full administrative view of one clothing item (flat category context)."""

    item_id: uuid.UUID
    name: str
    description: str | None = None
    category_id: int
    category_name: str
    slot: AvatarSlot
    price: int
    image_url: str
    availability_status: ClothingAvailability
    collection_id: uuid.UUID | None = None
    created_at: datetime


class ClothingAdminList(BaseModel):
    """Paginated response of GET /admin/clothing.

    total counts items matching the current search/filters regardless of
    availability (unlike public browse, admins see the whole catalog).
    """

    items: list[ClothingAdminRead]
    total: int
    limit: int
    offset: int
