"""
Pydantic schemas for the admin product-management module.

Input schemas only accept name/sku — there is deliberately no product_id
or created_at field, so a client can neither set nor change them (they
are owned by the database). Output schemas add qr_code_count so an
administrator can see whether a product is referenced before attempting
a delete; they expose nothing else internal.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, field_validator


def _require_non_empty(value: str) -> str:
    stripped = value.strip()
    if not stripped:
        raise ValueError("must not be empty")
    return stripped


class ProductAdminCreate(BaseModel):
    """Body of POST /admin/products. product_id and created_at are
    generated by the database — a client cannot supply them."""

    name: str = Field(max_length=255, description="Product display name")
    sku: str = Field(max_length=100, description="Unique stock-keeping unit code")

    @field_validator("name", "sku")
    @classmethod
    def non_empty(cls, value: str) -> str:
        return _require_non_empty(value)


class ProductAdminUpdate(BaseModel):
    """Body of PATCH /admin/products/{product_id}.

    Both fields optional (single-field PATCH). Only name/sku can change;
    product_id and created_at are immutable and cannot be referenced.
    """

    name: str | None = Field(default=None, max_length=255)
    sku: str | None = Field(default=None, max_length=100)

    @field_validator("name", "sku")
    @classmethod
    def non_empty(cls, value: str | None) -> str | None:
        if value is None:
            return None
        return _require_non_empty(value)


class ProductAdminRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    product_id: uuid.UUID
    name: str
    sku: str
    created_at: datetime
    qr_code_count: int


class ProductAdminList(BaseModel):
    """Paginated response of GET /admin/products."""

    items: list[ProductAdminRead]
    total: int
    limit: int
    offset: int